Repository 2ana9/delievery-management, pull requests merged in 2025-02, with the labels that each got.

#44 - 모든 주소 정보 엘라스틱 서치로 가져오도록 처리
  build.gradle
  src/main/java/com/ana29/deliverymanagement/config/ElasticsearchConfig.java
  src/main/java/com/ana29/deliverymanagement/config/jwt/WebSecurityConfig.java
  src/main/java/com/ana29/deliverymanagement/controller/AreaController.java
  src/main/java/com/ana29/deliverymanagement/dto/AreaRequestDto.java
  src/main/java/com/ana29/deliverymanagement/entity/Area.java
  src/main/java/com/ana29/deliverymanagement/entity/AreaDocument.java
  src/main/java/com/ana29/deliverymanagement/repository/AreaRepository.java
  src/main/java/com/ana29/deliverymanagement/repository/AreaSearchRepository.java
  src/main/java/com/ana29/deliverymanagement/service/AreaService.java
Labels: enhancement

#74 refactor(orderapi) : 응답 표준화 (리팩토링)
  src/main/java/com/ana29/deliverymanagement/global/dto/ResponseDto.java
  src/main/java/com/ana29/deliverymanagement/order/controller/OrderController.java
Labels: duplicate

#103 Feat/#94 get restaurant order api
  src/main/java/com/ana29/deliverymanagement/order/controller/OrderController.java
Labels: duplicate

#127 Review 도메인 리팩토링, 서치기능 조건 추가
  src/main/java/com/ana29/deliverymanagement/restaurant/repository/RestaurantRepositoryCustomImpl.java
  src/main/java/com/ana29/deliverymanagement/review/controller/ReviewController.java
  src/main/java/com/ana29/deliverymanagement/review/dto/CreateReviewRequestDto.java
  src/main/java/com/ana29/deliverymanagement/review/dto/ReviewDetailResponseDto.java
  src/main/java/com/ana29/deliverymanagement/review/dto/ReviewSearchCondition.java
  src/main/java/com/ana29/deliverymanagement/review/dto/UpdateReviewRequestDto.java
  src/main/java/com/ana29/deliverymanagement/review/entity/Review.java
  src/main/java/com/ana29/deliverymanagement/review/exception/ReviewAccessDeniedException.java
  src/main/java/com/ana29/deliverymanagement/review/repository/ReviewRepository.java
  src/main/java/com/ana29/deliverymanagement/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/ana29/deliverymanagement/review/repository/ReviewRepositoryCustomImpl.java
  src/main/java/com/ana29/deliverymanagement/review/service/ReviewService.java
Labels: refactor

#133 Refactoring/#68 refactoring
  src/main/java/com/ana29/deliverymanagement/Application.java
  src/main/java/com/ana29/deliverymanagement/data/DatabaseInitializer.java
  src/main/java/com/ana29/deliverymanagement/data/RedisCacheInitializer.java
  src/main/java/com/ana29/deliverymanagement/security/config/WebSecurityConfig.java
  src/main/java/com/ana29/deliverymanagement/security/constant/jwt/JwtConfigEnum.java
  src/main/java/com/ana29/deliverymanagement/security/jwt/.gitkeep
  src/main/java/com/ana29/deliverymanagement/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/ana29/deliverymanagement/security/jwt/RedisTokenBlacklist.java
  src/main/java/com/ana29/deliverymanagement/security/jwt/TokenBlacklist.java
  src/main/java/com/ana29/deliverymanagement/security/scheduler/Scheduler.java
  src/main/java/com/ana29/deliverymanagement/security/service/CachedUserDetailsService.java
  src/main/java/com/ana29/deliverymanagement/user/controller/UserController.java
  src/main/java/com/ana29/deliverymanagement/user/entity/User.java
  src/main/java/com/ana29/deliverymanagement/user/repository/UserRepository.java
  src/main/java/com/ana29/deliverymanagement/user/service/UserAddressService.java
  src/main/java/com/ana29/deliverymanagement/user/service/Userservice.java
Labels: bug, refactor

#159 index.adoc에 리뷰 추가
  src/docs/asciidoc/index.adoc
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: documentation
